openapi: 3.0.0
info:
  title: 샘플 API
  version: 1.0.0
  description: 이것은 샘플 API입니다.
tags:
  - name: User
    description: 사용자 관련 API
paths:
  /users:
    get:
      tags:
        - User
      summary: 사용자 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: 사용자 ID
        name:
          type: string
          description: 사용자 이름